# Generated by Django 4.2.7 on 2023-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('course_length', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
    ]
